In [26]:
import numpy as np
arr = np.array([5, 12, 18, 7, 30, 25])
arr_num = np.where(arr > 10) and (arr < 20)
print(arr[arr_num])

[ 5 12 18  7]


In [37]:
arr = np.array([10, 15, 20, 25, 30, 35])

arr_num = np.where(arr <= 15) or (arr >= 30)
print(arr[arr_num])

[10 15]


In [34]:
arr = np.array([3, 8, 15, 6, 2, 20])
arr_num = np.where(arr >= 10, 0, arr) 

print(arr_num)


[3 8 0 6 2 0]


In [40]:
arr = np.array([7, 14, 21, 28, 35])
arr_num = np.where(arr >= 20, "High", "Low") 

print(arr_num)

['Low' 'Low' 'High' 'High' 'High']


In [41]:
arr = np.arange(0, 10)
arr_num = np.where(arr % 2 == 1, arr * 10, arr)
print(arr_num)

[ 0 10  2 30  4 50  6 70  8 90]


In [46]:
arr = np.array([[10, 25, 30],
                [40, 5, 15],
                [20, 35, 50]])
arr_num = np.where((arr >= 20) & (arr <= 40), arr, 0)
print(arr_num)

[[ 0 25 30]
 [40  0  0]
 [20 35  0]]


In [52]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr_num = np.where(~(arr  % 3 == 0), arr, 0)
print(arr_num)

[1 2 0 4 5 0]


In [2]:
import numpy as np
from numpy.random import default_rng

rng = np.random.default_rng(seed=42)
arr = rng.integers(0, 101, size=10)
arr_num = np.where(arr < 50, arr, 50)  
print(arr_num)

[ 9 50 50 44 43 50  8 50 20  9]


In [6]:
arr = np.array( [[5, 50, 95],
                 [20, 75, 10],
                 [60, 30, 85]])
arr_num = arr_num = np.where(arr > 70, "A",
          np.where((arr >= 30) & (arr < 70), "B", "C")) 
alpha = ["A", "B", "C"]
print(arr_num)


[['C' 'B' 'A']
 ['C' 'A' 'C']
 ['B' 'B' 'A']]


In [15]:
arr1 = np.arange(1, 10).reshape(3, 3)
arr2 = np.full((3, 2), 2)
print(np.matmul(arr1, arr2))

[[12 12]
 [30 30]
 [48 48]]


In [ ]:
import numpy as np
from numpy.random import default_rng

rng = default_rng(seed = 42)

I = np.eye(4, dtype=int)
M = np.random.randint(0, 10, (4, 4))
print(I)
print(M)
print(np.matmul(I, M))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[7 5 4 2]
 [0 1 4 1]
 [3 5 6 2]
 [3 5 7 3]]
[[7 5 4 2]
 [0 1 4 1]
 [3 5 6 2]
 [3 5 7 3]]


In [37]:
X_array = np.full((2, 5), 1)
Y_array = np.arange(5, 15).reshape(5, 2)
print(X_array)
print(Y_array)
print(np.matmul(X_array, Y_array))

[[1 1 1 1 1]
 [1 1 1 1 1]]
[[ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]
[[45 50]
 [45 50]]


In [44]:
import numpy as np
from numpy.random import default_rng

rng = default_rng(seed = 42)

C_array = np.random.randint(0, 5, (3, 2))
D_array = np.random.randint(0, 5, (2, 3))
print(np.matmul(C_array, D_array).shape)
print(np.matmul(C_array, D_array))


(3, 3)
[[ 5 11 20]
 [ 6 16 24]
 [ 4 10 16]]
