# **1. Numpy(넘파이)** 

+ 데이터 연산, 데이터 분석, 데이터 과학, 머신러닝 과학 연구 분야에 사용되는 패키지 
+ 파이썬는 인터프리터 언어로 실행이 느림 
+ numpy는 c언어로 구현되어 있어 대용량 데이터 연산을 매우 빠르게 처리 
+ 속도 문제 해결을 위해 사용(메모리 효율성)
    + 파이썬 리스트: 각 요소가 객체로 저장되어 메모리가 오버헤드됨 
    + numpy 배열: 연속된 메모리 동간에 같은 타입의 데이터를 저장 
+ 벡터화 연산
    + 반복문 없이 전체 배열에 대한 연산을 한 번에 수행 
+ 설치: pip install numpy

In [9]:
import numpy as np
print('numpy 버전: ', np.__version__)
print('numpy 설치 경로: ', np.__file__)

arr = np.array([1, 2, 3, 4, 5])
print("1. 객체 타입: ", type(arr))
print("2. 데이터 타입: ", arr.dtype)
print("3. 배열 모양: ", arr.shape)
print("4. 차원 수: ", arr.ndim)
print("5. 전체 요소 수: ", arr.size)

python_list = [1, 1.25, "3.", True]
numpy_array = np.array([1, 1.25, "3.", True])
print("파이썬 리스트: ", python_list)
print("Numpy 배열: ", numpy_array)

list1 = [1, 2, 3]
list2 = [4, 5, 6]
print('리스트 더하기: ', list1 + list2)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print('numpy 배열 더하기: ', arr1 + arr2)


numpy 버전:  1.26.4
numpy 설치 경로:  c:\Anaconda\Lib\site-packages\numpy\__init__.py
1. 객체 타입:  <class 'numpy.ndarray'>
2. 데이터 타입:  int32
3. 배열 모양:  (5,)
4. 차원 수:  1
5. 전체 요소 수:  5
파이썬 리스트:  [1, 1.25, '3.', True]
Numpy 배열:  ['1' '1.25' '3.' 'True']
리스트 더하기:  [1, 2, 3, 4, 5, 6]
numpy 배열 더하기:  [5 7 9]


In [10]:
int_array = np.array([1, 2, 3, 4, 5])
print('정수 배열: ', int_array)
print('데이터 타입: ', int_array.dtype)

float_array = np.array([1.1, 2.2, 3.3, 4.4, 5])
print('정수 배열: ', float_array)
print('데이터 타입: ', float_array.dtype)

정수 배열:  [1 2 3 4 5]
데이터 타입:  int32
정수 배열:  [1.1 2.2 3.3 4.4 5. ]
데이터 타입:  float64


In [75]:
specified_array = np.array(["1", "2", 3, 4, 5], dtype=np.float32)
print('명시적 배열: ', specified_array)
print('데이터 타입: ', specified_array.dtype)

string_array = np.array(['apple', 'banana', 'cherry'])
print('문자열 배열: ', string_array)
print('데이터 타입: ', string_array.dtype)

matrix = np.array([
    [1, 2, 3],
    [2, 3, 4],
    [4, 5, 6]
])

print("2차원 배열: ",matrix)
print("모양: ",matrix.shape)
print("차원: ",matrix.ndim)
print("크기: ",matrix.size)

# for i in range(3):
#     for j in range(3):
#         print()


rows = []
for i in range(3):
    row = [i * 3 + j for j in range(4)]
    rows.append(row)

matrix2 = np.array(rows)
print("동적 생성 행렬: ", matrix2)


tensor = np.array([
    [
        [1, 2, 3, 4], 
        [5, 6, 7, 8], 
        [9, 10, 11, 12], 
    ],

])
print("3차원 배열 모양: ", tensor.shape)
print("차원: ", tensor.ndim)
print()

arr1 = np.arange(10)
print('0부터 9까지: ', arr1)
arr2 = np.arange(1, 11)
print("1부터 10까지: ", arr2)
arr3 = np.arange(1, 21, 2)
print("1부터 20까지: ", arr3)
arr4 = np.arange(1, 11, 0.5)
print("1부터 10까지 0.5씩 증가: ", arr4)

print()
arr1 = np.linspace(0, 9, 5, endpoint=False)
print("0부터 10까지 5개 요소\n", arr1)



명시적 배열:  [1. 2. 3. 4. 5.]
데이터 타입:  float32
문자열 배열:  ['apple' 'banana' 'cherry']
데이터 타입:  <U6
2차원 배열:  [[1 2 3]
 [2 3 4]
 [4 5 6]]
모양:  (3, 3)
차원:  2
크기:  9
동적 생성 행렬:  [[0 1 2 3]
 [3 4 5 6]
 [6 7 8 9]]
3차원 배열 모양:  (1, 3, 4)
차원:  3

0부터 9까지:  [0 1 2 3 4 5 6 7 8 9]
1부터 10까지:  [ 1  2  3  4  5  6  7  8  9 10]
1부터 20까지:  [ 1  3  5  7  9 11 13 15 17 19]
1부터 10까지 0.5씩 증가:  [ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5]

0부터 10까지 5개 요소
 [0.  1.8 3.6 5.4 7.2]


In [46]:
arr1 = np.linspace(0, 10, 5, endpoint=False)
print("0부터 10까지 5개 요소 끝값 제외 \n", arr1)

0부터 10까지 5개 요소 끝값 제외 
 [0. 2. 4. 6. 8.]


In [53]:
zeros_1d = np.zeros(5)
print("1차원 zeros: ", zeros_1d)

zeros_2d = np.zeros((3, 4))
print("2차원 zeros: ", zeros_2d)
zeros_2d_int = np.zeros((3, 4), dtype=int)
print("2차원 zeros: ", zeros_2d_int)


matrix = np.array([
        [1, 2, 3], 
        [2, 3, 4], 
        [4, 5, 6], 
    ])

zeros_copy = np.zeros_like(matrix)
print("zeros_like: ", zeros_copy)

1차원 zeros:  [0. 0. 0. 0. 0.]
2차원 zeros:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2차원 zeros:  [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
zeros_like:  [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [70]:
print(np.arange(0, 22, 2))

[ 0  2  4  6  8 10 12 14 16 18 20]


In [161]:
import numpy as np

zero_1 = np.full((3, 4), 0)
print("문제 1 과정: \n", zero_1)
print()
zero_2 = np.full(zero_1.shape, 5)
print("문제 1: \n", zero_2)


문제 1 과정: 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

문제 1: 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [162]:
import numpy as np
print("문제 2: \n", np.arange(0, 22, 2))

문제 2: 
 [ 0  2  4  6  8 10 12 14 16 18 20]


In [163]:
from numpy.random import default_rng

rng = default_rng(seed = 42)
print("문제 3: \n", rng.random((2, 3)))

문제 3: 
 [[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]


In [164]:
from numpy.random import default_rng

rng = default_rng(seed = 42)

number = rng.normal(100, 20, size = 6)
print("문제 4: \n", number)

문제 4: 
 [106.0943416   79.20031788 115.00902392 118.81129433  60.97929623
  73.95640986]


In [166]:
import numpy as np

number1 = np.arange(1, 21)
print("문제 5 과정: ", number1)
print()

print("문제 5:\n", number1.reshape(4, 5))


문제 5 과정:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

문제 5:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [167]:
import numpy as np

number = np.linspace(0, 1, 12).reshape(3, 4)
print("문제 6: \n", number)

문제 6: 
 [[0.         0.09090909 0.18181818 0.27272727]
 [0.36363636 0.45454545 0.54545455 0.63636364]
 [0.72727273 0.81818182 0.90909091 1.        ]]


In [168]:
import numpy as np

number = np.random.randint(0, 100, (10, 10))
a = np.eye(10, dtype = int)
result = number + a
print("문제 7과정: \n")
print(number)
print()
print(a)
print()
print("문제 7: \n", result)
print()

문제 7과정: 

[[20 52 89 28 76  2 80 62 19 33]
 [94 75 94 70 19 23 37 83 48 52]
 [96 24 98 57 38 18 62 21 26 51]
 [97 48 20  0 45 78 43  3 17 28]
 [95 73  5 65 77  7 94 67 44  6]
 [47 37 55 17 10 22 27 85 13 72]
 [20 39 67  1 30 76 47 49 49 26]
 [45 79 50 67 16 98 56 38 36 27]
 [69 31 80 31 33 86 93 11  2 53]
 [68 16 38 23 24 33  8 19 90 39]]

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]

문제 7: 
 [[21 52 89 28 76  2 80 62 19 33]
 [94 76 94 70 19 23 37 83 48 52]
 [96 24 99 57 38 18 62 21 26 51]
 [97 48 20  1 45 78 43  3 17 28]
 [95 73  5 65 78  7 94 67 44  6]
 [47 37 55 17 10 23 27 85 13 72]
 [20 39 67  1 30 76 48 49 49 26]
 [45 79 50 67 16 98 56 39 36 27]
 [69 31 80 31 33 86 93 11  3 53]
 [68 16 38 23 24 33  8 19 90 40]]



In [169]:
import numpy as np

number = np.random.randint(0, 10, (2, 3, 4))
print("문제 8: \n", number)

문제 8: 
 [[[6 1 8 2]
  [9 7 4 4]
  [6 1 6 2]]

 [[2 2 7 0]
  [4 8 0 8]
  [9 3 0 3]]]


In [170]:
import numpy as np
arr = np.arange(10, 30, 2)
print(arr[[1, 3, 5]])

[12 16 20]
