# **1. Numpy(넘파이)** 

+ 데이터 연산, 데이터 분석, 데이터 과학, 머신러닝 과학 연구 분야에 사용되는 패키지 
+ 파이썬는 인터프리터 언어로 실행이 느림 
+ numpy는 c언어로 구현되어 있어 대용량 데이터 연산을 매우 빠르게 처리 
+ 속도 문제 해결을 위해 사용(메모리 효율성)
    + 파이썬 리스트: 각 요소가 객체로 저장되어 메모리가 오버헤드됨 
    + numpy 배열: 연속된 메모리 동간에 같은 타입의 데이터를 저장 
+ 벡터화 연산
    + 반복문 없이 전체 배열에 대한 연산을 한 번에 수행 
+ 설치: pip install numpy

In [1]:
import numpy as np
print('numpy 버전: ', np.__version__)
print('numpy 설치 경로: ', np.__file__)

arr = np.array([1, 2, 3, 4, 5])
print("1. 객체 타입: ", type(arr))
print("2. 데이터 타입: ", arr.dtype)
print("3. 배열 모양: ", arr.shape)
print("4. 차원 수: ", arr.ndim)
print("5. 전체 요소 수: ", arr.size)

python_list = [1, 1.25, "3.", True]
numpy_array = np.array([1, 1.25, "3.", True])
print("파이썬 리스트: ", python_list)
print("Numpy 배열: ", numpy_array)

list1 = [1, 2, 3]
list2 = [4, 5, 6]
print('리스트 더하기: ', list1 + list2)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print('numpy 배열 더하기: ', arr1 + arr2)


numpy 버전:  1.26.4
numpy 설치 경로:  c:\Anaconda\Lib\site-packages\numpy\__init__.py
1. 객체 타입:  <class 'numpy.ndarray'>
2. 데이터 타입:  int32
3. 배열 모양:  (5,)
4. 차원 수:  1
5. 전체 요소 수:  5
파이썬 리스트:  [1, 1.25, '3.', True]
Numpy 배열:  ['1' '1.25' '3.' 'True']
리스트 더하기:  [1, 2, 3, 4, 5, 6]
numpy 배열 더하기:  [5 7 9]


In [2]:
int_array = np.array([1, 2, 3, 4, 5])
print('정수 배열: ', int_array)
print('데이터 타입: ', int_array.dtype)

float_array = np.array([1.1, 2.2, 3.3, 4.4, 5])
print('정수 배열: ', float_array)
print('데이터 타입: ', float_array.dtype)

정수 배열:  [1 2 3 4 5]
데이터 타입:  int32
정수 배열:  [1.1 2.2 3.3 4.4 5. ]
데이터 타입:  float64


In [3]:
specified_array = np.array(["1", "2", 3, 4, 5], dtype=np.float32)
print('명시적 배열: ', specified_array)
print('데이터 타입: ', specified_array.dtype)

string_array = np.array(['apple', 'banana', 'cherry'])
print('문자열 배열: ', string_array)
print('데이터 타입: ', string_array.dtype)

matrix = np.array([
    [1, 2, 3],
    [2, 3, 4],
    [4, 5, 6]
])

print("2차원 배열: ",matrix)
print("모양: ",matrix.shape)
print("차원: ",matrix.ndim)
print("크기: ",matrix.size)

# for i in range(3):
#     for j in range(3):
#         print()


rows = []
for i in range(3):
    row = [i * 3 + j for j in range(4)]
    rows.append(row)

matrix2 = np.array(rows)
print("동적 생성 행렬: ", matrix2)


tensor = np.array([
    [
        [1, 2, 3, 4], 
        [5, 6, 7, 8], 
        [9, 10, 11, 12], 
    ],

])
print("3차원 배열 모양: ", tensor.shape)
print("차원: ", tensor.ndim)
print()

arr1 = np.arange(10)
print('0부터 9까지: ', arr1)
arr2 = np.arange(1, 11)
print("1부터 10까지: ", arr2)
arr3 = np.arange(1, 21, 2)
print("1부터 20까지: ", arr3)
arr4 = np.arange(1, 11, 0.5)
print("1부터 10까지 0.5씩 증가: ", arr4)

print()
arr1 = np.linspace(0, 9, 5, endpoint=False)
print("0부터 10까지 5개 요소\n", arr1)



명시적 배열:  [1. 2. 3. 4. 5.]
데이터 타입:  float32
문자열 배열:  ['apple' 'banana' 'cherry']
데이터 타입:  <U6
2차원 배열:  [[1 2 3]
 [2 3 4]
 [4 5 6]]
모양:  (3, 3)
차원:  2
크기:  9
동적 생성 행렬:  [[0 1 2 3]
 [3 4 5 6]
 [6 7 8 9]]
3차원 배열 모양:  (1, 3, 4)
차원:  3

0부터 9까지:  [0 1 2 3 4 5 6 7 8 9]
1부터 10까지:  [ 1  2  3  4  5  6  7  8  9 10]
1부터 20까지:  [ 1  3  5  7  9 11 13 15 17 19]
1부터 10까지 0.5씩 증가:  [ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5]

0부터 10까지 5개 요소
 [0.  1.8 3.6 5.4 7.2]


In [4]:
arr1 = np.linspace(0, 10, 5, endpoint=False)
print("0부터 10까지 5개 요소 끝값 제외 \n", arr1)

0부터 10까지 5개 요소 끝값 제외 
 [0. 2. 4. 6. 8.]


In [5]:
zeros_1d = np.zeros(5)
print("1차원 zeros: ", zeros_1d)

zeros_2d = np.zeros((3, 4))
print("2차원 zeros: ", zeros_2d)
zeros_2d_int = np.zeros((3, 4), dtype=int)
print("2차원 zeros: ", zeros_2d_int)


matrix = np.array([
        [1, 2, 3], 
        [2, 3, 4], 
        [4, 5, 6], 
    ])

zeros_copy = np.zeros_like(matrix)
print("zeros_like: ", zeros_copy)

1차원 zeros:  [0. 0. 0. 0. 0.]
2차원 zeros:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2차원 zeros:  [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
zeros_like:  [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
print(np.arange(0, 22, 2))

[ 0  2  4  6  8 10 12 14 16 18 20]


In [7]:
# ============================================================================
# NumPy (Numerical Python) 완벽 가이드
# ============================================================================

# python -m venv 폴더이름
# python -m venv venv

# ============================================================================
# 1. NumPy란 무엇인가?
# ============================================================================
"""
NumPy는 파이썬에서 과학계산을 위한 핵심 라이브러리입니다.
데이터과학, 머신러닝, 과학 연구 분야에서 가장 중요한 도구 중 하나입니다.

주요 특징:
1. 다차원 배열 객체 (ndarray)
2. 빠른 연산 속도
3. 메모리 효율성
4. 벡터화 연산 지원
5. 선형대수, 푸리에 변환, 난수 생성 등 다양한 수학 함수 제공
"""

# ============================================================================
# 2. 왜 NumPy를 사용해야 하는가?
# ============================================================================
"""
문제점: 파이썬은 인터프리터 언어로 실행속도가 느립니다.

해결책 1 - 속도 개선:
- NumPy는 C언어로 구현되어 있어 대용량 데이터 연산을 매우 빠르게 처리
- 일반 파이썬 리스트보다 10~100배 이상 빠름

해결책 2 - 메모리 효율성:
- 파이썬 리스트: 각 요소가 객체로 저장되어 메모리 오버헤드가 큼
  예) [1, 2, 3] → 각 숫자가 별도의 파이썬 객체로 저장
- NumPy 배열: 연속된 메모리 공간에 같은 타입의 데이터를 저장
  예) array([1, 2, 3]) → 연속된 메모리에 정수만 저장

해결책 3 - 벡터화 연산:
- 반복문 없이 전체 배열에 대한 연산을 한번에 수행
- 코드가 간결하고 가독성이 좋음
"""


import numpy as np
print('Numpy 버전:', np.__version__)
print('Numpy 설치 경로:', np.__file__)
print()

# ============================================================================
# 3. ndarray - NumPy의 핵심 자료구조
# ============================================================================
"""
ndarray (N-dimensional array):
- NumPy의 핵심 자료구조
- 같은 타입의 요소들을 담는 다차원 컨테이너
- 고정된 크기의 동질적인(homogeneous) 배열

핵심 속성:
- dtype: 배열 요소의 데이터 타입
- shape: 배열의 형태 (각 차원의 크기)
- ndim: 배열의 차원 수
- size: 배열의 전체 요소 개수
- itemsize: 각 요소의 바이트 크기
"""

arr = np.array([1, 2, 3, 4, 5])

print('=== ndarray 기본 속성 ===')
print('1. 객체 타입:', type(arr))  # <class 'numpy.ndarray'>
print('2. 데이터 타입:', arr.dtype)  # int64 (64비트 정수)
print('3. 배열 모양:', arr.shape)  # (5,) - 1차원 배열, 5개 요소
print('4. 차원 수:', arr.ndim)  # 1 - 1차원
print('5. 전체 요소 수:', arr.size)  # 5개
print()

# ============================================================================
# 4. 파이썬 리스트 vs NumPy 배열
# ============================================================================
"""
중요한 차이점을 이해하는 것이 NumPy 학습의 첫걸음입니다.
"""

print('=== 차이점 1: 타입 고정성 ===')
"""
파이썬 리스트:
- 서로 다른 타입의 요소를 담을 수 있음 (이질적)
- 각 요소가 독립적인 파이썬 객체
- 유연하지만 메모리와 속도 측면에서 비효율적

NumPy 배열:
- 모든 요소가 같은 타입이어야 함 (동질적)
- 다른 타입이 섞이면 자동으로 상위 타입으로 변환
- 변환 우선순위: bool < int < float < complex < string
"""
python_list = [1, 2.5, '3', True]  # 다양한 타입 가능
numpy_array = np.array([1, 2, 3, True])  # True는 1로 변환됨
print('파이썬 리스트:', python_list)
print('Numpy 배열:', numpy_array)  # [1 2 3 1] - 모두 정수로 통일
print()

print('=== 차이점 2: 연산 방식 ===')
"""
파이썬 리스트 + 연산:
- 리스트 연결(concatenation)
- [1,2,3] + [4,5,6] = [1,2,3,4,5,6]

NumPy 배열 + 연산:
- 요소별(element-wise) 연산
- [1,2,3] + [4,5,6] = [5,7,9]
- 벡터화 연산으로 매우 빠름
"""
list1 = [1, 2, 3]
list2 = [4, 5, 6]
print('리스트 더하기:', list1 + list2)  # [1, 2, 3, 4, 5, 6] - 연결

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print('Numpy 배열 더하기:', arr1 + arr2)  # [5 7 9] - 요소별 덧셈
print()

# ============================================================================
# 5. 다양한 데이터 타입의 배열 생성
# ============================================================================
"""
NumPy는 다양한 데이터 타입을 지원합니다:
- 정수형: int8, int16, int32, int64
- 부동소수점: float16, float32, float64
- 복소수: complex64, complex128
- 불린: bool
- 문자열: string_, unicode_
"""

print('=== 정수 배열 ===')
int_array = np.array([1, 2, 3, 4, 5])
print('정수 배열:', int_array)
print('데이터 타입:', int_array.dtype)  # int64 (시스템에 따라 다를 수 있음)
print()

print('=== 실수 배열 ===')
"""
실수가 하나라도 포함되면 전체가 실수형으로 변환됩니다.
"""
float_array = np.array([1.1, 2.2, 3.3, 4.4, 5])
print('실수 배열:', float_array)
print('데이터 타입:', float_array.dtype)  # float64
print()

print('=== 명시적 타입 지정 ===')
"""
dtype 매개변수로 원하는 데이터 타입을 명시적으로 지정할 수 있습니다.
장점:
- 메모리 절약 (float32는 float64의 절반 메모리 사용)
- 호환성 (특정 라이브러리나 하드웨어 요구사항 충족)
"""
specified_array = np.array(['1', '2', 3, 4, 5], dtype=np.float32)
print('명시적 배열:', specified_array)
print('데이터 타입:', specified_array.dtype)  # float32
print()

print('=== 문자열 배열 ===')
"""
<U10 의미:
- <: little-endian (바이트 순서)
- U: 유니코드 문자열
- 10: 최대 문자 길이
"""
string_array = np.array(['apple', 'banana', 'cherry'])
print('문자열 배열:', string_array)
print('데이터 타입:', string_array.dtype)  # <U6 (가장 긴 문자열 기준)
print()

# ============================================================================
# 6. 다차원 배열
# ============================================================================
"""
NumPy의 진정한 힘은 다차원 배열 처리에서 나타납니다.

1차원 배열: 벡터 (vector)
2차원 배열: 행렬 (matrix)
3차원 배열: 텐서 (tensor)
4차원 이상: 고차원 텐서
"""

print('=== 2차원 배열 (행렬) ===')
"""
행렬 표현:
[1, 2, 3]
[2, 3, 4]
[4, 5, 6]

shape (3, 3) 의미:
- 첫 번째 3: 행(row)의 개수
- 두 번째 3: 열(column)의 개수
"""
matrix = np.array([
    [1, 2, 3],
    [2, 3, 4],
    [4, 5, 6]
])

print('2차원 배열:\n', matrix)
print('모양:', matrix.shape)  # (3, 3) - 3행 3열
print('차원:', matrix.ndim)  # 2 - 2차원
print('크기:', matrix.size)  # 9 - 총 9개 요소
print()

print('=== 반복문으로 배열 생성 ===')
"""
프로그래밍 방식으로 배열을 생성할 수 있습니다.
실무에서 데이터를 동적으로 생성할 때 유용합니다.
"""
rows = []
for i in range(3):
    row = [i * 3 + j for j in range(4)]  # [0, 1, 2, 3], [3, 4, 5, 6], ...
    rows.append(row)

matrix2 = np.array(rows)
print('동적 생성 행렬:\n', matrix2)
print()

print('=== 3차원 배열 (텐서) ===')
"""
3차원 배열의 이해:
- 여러 개의 2차원 행렬을 쌓은 형태
- 이미지 처리: (높이, 너비, 색상채널)
- 동영상 처리: (프레임, 높이, 너비)
- 딥러닝: (배치크기, 높이, 너비)

shape (2, 3, 4) 의미:
- 2: 2개의 행렬
- 3: 각 행렬은 3행
- 4: 각 행렬은 4열
"""
tensor = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24],
    ],
])

print('3차원 배열 모양:', tensor.shape)  # (2, 3, 4)
print('차원:', tensor.ndim)  # 3
print('크기:', tensor.size)  # 24개 요소
print()

# ============================================================================
# 7. NumPy 내장 함수로 배열 생성
# ============================================================================

print('=== arange: 연속된 숫자 배열 ===')
"""
np.arange(start, stop, step)
- 파이썬 range()와 유사하지만 NumPy 배열 반환
- stop 값은 포함되지 않음 (미만)
- step에 실수도 사용 가능
"""
arr1 = np.arange(10)  # 0부터 9까지
print('0부터 9까지:', arr1)

arr2 = np.arange(1, 11)  # 1부터 10까지
print('1부터 10까지:', arr2)

arr3 = np.arange(1, 21, 2)  # 1, 3, 5, ..., 19
print('1부터 20까지 홀수만:', arr3)

arr4 = np.arange(1, 11, 0.5)  # 0.5 간격
print('1부터 11까지 0.5 간격:', arr4)
print()

print('=== linspace: 균등 간격 배열 ===')
"""
np.linspace(start, stop, num, endpoint=True)
- 시작과 끝 사이를 균등하게 나눈 숫자들
- num: 생성할 요소의 개수
- endpoint=True: 끝값 포함 (기본값)
- endpoint=False: 끝값 미포함

계산 공식:
- endpoint=True: step = (stop - start) / (num - 1)
- endpoint=False: step = (stop - start) / num

사용 예시:
- 그래프 그리기 (x축 좌표 생성)
- 수치해석 (등간격 샘플링)
- 신호처리 (시간 축 생성)
"""
arr1 = np.linspace(0, 10, 5)  # 0, 2.5, 5, 7.5, 10
print('0부터 10까지 5개 요소:', arr1)

arr2 = np.linspace(0, 10, 5, endpoint=False)  # 0, 2, 4, 6, 8
print('끝값 제외:', arr2)
print()

print('=== zeros: 0으로 채운 배열 ===')
"""
용도:
- 배열 초기화
- 누적 계산용 배열 준비
- 이미지 처리 (검은색 이미지 생성)
"""
zeros_1d = np.zeros(5)
print('1차원 zeros:', zeros_1d)

zeros_2d = np.zeros((3, 4))
print('2차원 zeros:\n', zeros_2d)

zeros_2d_int = np.zeros((3, 4), dtype=int)
print('2차원 zeros (정수):\n', zeros_2d_int)

matrix = np.array([
    [1, 2, 3],
    [2, 3, 4],
    [4, 5, 6]
])
# 기존 배열과 같은 모양의 영 배열
zeros_copy = np.zeros_like(matrix)
print('zeros_like:\n', zeros_copy)
print()

print('=== ones: 1로 채운 배열 ===')
"""
용도:
- 가중치 초기화
- 마스크 배열 생성
- 곱셈 항등원
"""
ones_1d = np.ones(5)
print('1차원 ones:', ones_1d)

ones_2d = np.ones((3, 4))
print('2차원 ones:\n', ones_2d)

ones_2d_bool = np.ones((3, 4), dtype=bool)
print('2차원 ones (불린):\n', ones_2d_bool)
print()

print('=== full: 특정 값으로 채운 배열 ===')
"""
용도:
- 초기값이 있는 배열 생성
- 기본값 설정
"""
full_array = np.full((3, 4), 7)
print('7로 채운 배열:\n', full_array)

matrix = np.array([
    [1, 2, 3],
    [2, 3, 4],
    [4, 5, 6]
])
full_like = np.full_like(matrix, 999)
print('999로 채운 배열:\n', full_like)
print()

print('=== empty: 빈 배열 (주의!) ===')
"""
주의사항:
- 메모리만 할당하고 초기화하지 않음
- 쓰레기 값(garbage value)이 들어있음
- 빠르지만 위험할 수 있음
- 반드시 나중에 값을 채워야 함

사용 시기:
- 즉시 값을 채울 예정일 때
- 속도가 매우 중요할 때
"""
empty_array = np.empty((2, 3))
print('빈 배열 (쓰레기값):\n', empty_array)
print()

print('=== eye: 단위 행렬 (항등 행렬) ===')
"""
단위 행렬 (Identity Matrix):
- 대각선은 1, 나머지는 0
- 행렬 곱셈의 항등원 (A × I = A)

용도:
- 선형대수 연산
- 머신러닝 초기화
- 공분산 행렬 생성
"""
identity = np.eye(3)
print('3x3 항등 행렬:\n', identity)

matrix = np.eye(4, 5)  # 4행 5열
print('4x5 대각 행렬:\n', matrix)

matrix = np.eye(4, k=1)  # 대각선을 위로 1칸 이동
print('위쪽 대각선:\n', matrix)

matrix = np.eye(4, k=-1)  # 대각선을 아래로 1칸 이동
print('아래쪽 대각선:\n', matrix)
print()

print('=== identity: 정방 항등 행렬 ===')
"""
eye와의 차이:
- identity는 정사각형만 생성 가능
- eye는 직사각형도 가능하고 대각선 위치 조정 가능
"""
identity = np.identity(4)
print('4x4 항등 행렬:\n', identity)
print()

# ============================================================================
# 8. 난수 생성
# ============================================================================

print('=== 균일 분포 난수 ===')
"""
균일 분포 (Uniform Distribution):
- 특정 구간 안에서 모든 값이 똑같은 확률로 나옴
- 치우침 없이 고르게 퍼져 있는 확률 분포

사용 예:
- 게임 개발 (랜덤 아이템 드롭)
- 시뮬레이션 (몬테카를로 방법)
- 초기화 (가중치 랜덤 초기화)
"""
random_uniform = np.random.rand(3, 3)  # 0~1 사이 균일 분포
print('0~1 균일 분포:\n', random_uniform)

rounded = np.round(random_uniform, 2)  # 소수점 2자리
print('0~1 균일 분포 (반올림):\n', rounded)

# 특정 범위로 스케일링
low, high = 10, 20
random_range = low + (high - low) * np.random.rand(3, 3)
print(f'{low}~{high} 균일 분포:\n', random_range)

# 더 직관적인 방법
uniform = np.random.uniform(low=0, high=100, size=(2, 3))
print('0~100 균일 분포:\n', uniform)
print()

print('=== 정규 분포 난수 ===')
"""
정규 분포 (Normal Distribution / Gaussian Distribution):
- 평균을 중심으로 좌우 대칭인 종 모양 분포
- 자연계의 많은 현상이 정규 분포를 따름
- 표준 정규 분포: 평균 0, 표준편차 1

68-95-99.7 규칙:
- 평균 ± 1σ: 68% 데이터
- 평균 ± 2σ: 95% 데이터
- 평균 ± 3σ: 99.7% 데이터

사용 예:
- 실제 데이터 시뮬레이션 (키, 몸무게, 시험 점수)
- 머신러닝 가중치 초기화
- 노이즈 추가
"""
random_normal1 = np.random.randn(3, 3)
print('표준 정규 분포:\n', random_normal1)

# 평균 100, 표준편차 15인 정규 분포 (예: 시험 점수)
mean, std = 100, 15
scores = mean + std * np.random.randn(1000)
print('시험 점수 시뮬레이션 (일부):', scores[:10])
print('실제 평균:', round(scores.mean(), 2))
print('실제 표준편차:', round(scores.std(), 2))
print()

print('=== 정수 난수 ===')
"""
randint(low, high, size)
- low 이상 high 미만의 정수
- 이산 균일 분포

사용 예:
- 게임 (주사위, 카드)
- 랜덤 샘플링
- 랜덤 인덱스 생성
"""
random_int = np.random.randint(0, 10, size=(3, 4))
print('0~9 정수 난수:\n', random_int)

# 주사위 시뮬레이션
dice = np.random.randint(1, 7, size=10)
print('주사위 10번 굴리기:', dice)
print()

print('=== 재현 가능한 난수 (시드 설정) ===')
"""
시드 (Seed):
- 난수 생성의 시작점
- 같은 시드 = 같은 난수 시퀀스
- 디버깅과 재현성을 위해 중요

사용 시기:
- 실험 재현
- 디버깅
- 테스트 코드 작성
"""
np.random.seed(42)  # 시드 고정
random1 = np.random.rand(5)
print('첫 번째 난수:', random1)

np.random.seed(42)  # 같은 시드 사용
random2 = np.random.rand(5)
print('두 번째 난수:', random2)
print('같은 난수인가?', np.array_equal(random1, random2))  # True
print()

print('=== 새로운 난수 생성 방식 (권장) ===')
"""
default_rng (Random Generator):
- NumPy 1.17 이상에서 권장하는 방식
- 더 나은 성능과 통계적 품질
- 여러 generator를 독립적으로 사용 가능

장점:
- 스레드 안전성
- 더 빠른 속도
- 더 좋은 난수 품질
"""
rng = np.random.default_rng(seed=42)
random3 = rng.random((2, 3))  # 0~1 균일 분포
print('새로운 방식 난수:\n', random3)

# 독립적인 generator 생성
rng1 = np.random.default_rng(seed=42)
rng2 = np.random.default_rng(seed=42)
print('독립적 generator 1:', rng1.random(3))
print('독립적 generator 2:', rng2.random(3))
print()

# ============================================================================
# 9. 핵심 정리
# ============================================================================
"""
NumPy 핵심 개념 요약:

1. ndarray는 동질적(같은 타입), 고정 크기의 다차원 배열
2. 파이썬 리스트보다 빠르고 메모리 효율적
3. 벡터화 연산으로 반복문 없이 전체 배열 연산 가능
4. dtype으로 데이터 타입 명시 가능
5. shape, ndim, size로 배열 구조 파악
6. 다양한 생성 함수: zeros, ones, arange, linspace 등
7. 난수 생성: 균일 분포, 정규 분포, 정수 난수
8. 시드 설정으로 재현 가능한 난수 생성

"""

print('=' * 70)
print('NumPy 기초 학습 완료!')
print('=' * 70)

Numpy 버전: 1.26.4
Numpy 설치 경로: c:\Anaconda\Lib\site-packages\numpy\__init__.py

=== ndarray 기본 속성 ===
1. 객체 타입: <class 'numpy.ndarray'>
2. 데이터 타입: int32
3. 배열 모양: (5,)
4. 차원 수: 1
5. 전체 요소 수: 5

=== 차이점 1: 타입 고정성 ===
파이썬 리스트: [1, 2.5, '3', True]
Numpy 배열: [1 2 3 1]

=== 차이점 2: 연산 방식 ===
리스트 더하기: [1, 2, 3, 4, 5, 6]
Numpy 배열 더하기: [5 7 9]

=== 정수 배열 ===
정수 배열: [1 2 3 4 5]
데이터 타입: int32

=== 실수 배열 ===
실수 배열: [1.1 2.2 3.3 4.4 5. ]
데이터 타입: float64

=== 명시적 타입 지정 ===
명시적 배열: [1. 2. 3. 4. 5.]
데이터 타입: float32

=== 문자열 배열 ===
문자열 배열: ['apple' 'banana' 'cherry']
데이터 타입: <U6

=== 2차원 배열 (행렬) ===
2차원 배열:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]
모양: (3, 3)
차원: 2
크기: 9

=== 반복문으로 배열 생성 ===
동적 생성 행렬:
 [[0 1 2 3]
 [3 4 5 6]
 [6 7 8 9]]

=== 3차원 배열 (텐서) ===
3차원 배열 모양: (2, 3, 4)
차원: 3
크기: 24

=== arange: 연속된 숫자 배열 ===
0부터 9까지: [0 1 2 3 4 5 6 7 8 9]
1부터 10까지: [ 1  2  3  4  5  6  7  8  9 10]
1부터 20까지 홀수만: [ 1  3  5  7  9 11 13 15 17 19]
1부터 11까지 0.5 간격: [ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   

In [8]:
import numpy as np

# ============================================================================
# np.random.normal() - 랜덤 숫자 만들기 (평균 중심)
# ============================================================================
"""
np.random.normal(평균, 범위, 개수)

쉽게 설명:
- 평균 주변에서 랜덤 숫자를 만들어줌
- 평균에서 멀어질수록 나올 확률이 낮아짐
- 예: 평균 키 170cm 주변에서 랜덤 키 만들기
"""

print('=== 1. 기본 사용법 ===')
# 평균 0 주변의 랜덤 숫자 10개
numbers = np.random.normal(size=10)
print('랜덤 숫자 10개:', numbers)
print()

print('=== 2. 평균 지정하기 ===')
# 평균 100 주변의 랜덤 숫자 10개 (예: 시험 점수)
scores = np.random.normal(loc=100, scale=15, size=10)
print('시험 점수 10개:', scores)
print('평균:', round(scores.mean(), 1))
print()

print('=== 3. 2차원 배열로 만들기 ===')
# 3행 4열의 랜덤 숫자
matrix = np.random.normal(loc=50, scale=10, size=(3, 4))
print('3x4 랜덤 배열:\n', matrix)
print()

print('=== 4. 실전 예제: 키 데이터 만들기 ===')
# 평균 키 170cm 주변에서 랜덤 키 100개 만들기
heights = np.random.normal(loc=170, scale=7, size=100)
print('키 10명:', [round(h, 1) for h in heights[:10]])
print('평균 키:', round(heights.mean(), 1), 'cm')
print('가장 큰 키:', round(heights.max(), 1), 'cm')
print('가장 작은 키:', round(heights.min(), 1), 'cm')
print()


# ============================================================================
# reshape() - 배열의 형태 변경
# ============================================================================
"""
array.reshape(new_shape)
또는
np.reshape(array, new_shape)

중요:
- 전체 요소 개수는 변하지 않음
- 원본 배열은 변경되지 않음 (새 view 반환)
- -1을 사용하면 자동으로 크기 계산
"""

print('=== 1. 기본 reshape ===')
# 1차원 → 2차원
arr = np.arange(12)  # [0, 1, 2, ..., 11]
print('원본 배열:', arr)
print('원본 shape:', arr.shape)  # (12,)

reshaped = arr.reshape(3, 4)  # 3행 4열
print('\n3x4로 변환:\n', reshaped)
print('변환 후 shape:', reshaped.shape)  # (3, 4)
print()

print('=== 2. 다양한 형태로 변환 ===')
arr = np.arange(24)

# 2차원 변환
matrix_2x12 = arr.reshape(2, 12)
print('2x12 행렬:\n', matrix_2x12)

matrix_4x6 = arr.reshape(4, 6)
print('\n4x6 행렬:\n', matrix_4x6)

matrix_6x4 = arr.reshape(6, 4)
print('\n6x4 행렬:\n', matrix_6x4)
print()

print('=== 3. 3차원으로 변환 ===')
# 24개 요소 → (2, 3, 4)
tensor = arr.reshape(2, 3, 4)
print('3차원 텐서 shape:', tensor.shape)
print('3차원 텐서:\n', tensor)
print()

print('=== 4. -1 사용: 자동 크기 계산 ===')
"""
-1의 의미:
- "나머지를 자동으로 계산해줘"
- 한 차원에만 사용 가능
- 전체 요소 개수를 기준으로 자동 계산

예: 12개 요소를 (3, -1)로 reshape
→ 12 / 3 = 4이므로 (3, 4)가 됨
"""
arr = np.arange(12)

auto_reshape1 = arr.reshape(3, -1)  # (3, 4)로 자동 계산
print('(3, -1) → shape:', auto_reshape1.shape)
print(auto_reshape1)

auto_reshape2 = arr.reshape(-1, 4)  # (3, 4)로 자동 계산
print('\n(-1, 4) → shape:', auto_reshape2.shape)
print(auto_reshape2)

auto_reshape3 = arr.reshape(2, 2, -1)  # (2, 2, 3)으로 자동 계산
print('\n(2, 2, -1) → shape:', auto_reshape3.shape)
print(auto_reshape3)
print()

print('=== 5. 1차원으로 펼치기 ===')
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print('원본 2차원 배열:\n', matrix)

# 방법 1: reshape(-1)
flattened1 = matrix.reshape(-1)
print('\nreshape(-1):', flattened1)

# 방법 2: flatten() - 복사본 생성
flattened2 = matrix.flatten()
print('flatten():', flattened2)

# 방법 3: ravel() - view 반환 (더 빠름)
flattened3 = matrix.ravel()
print('ravel():', flattened3)
print()

print('=== 6. 열 벡터, 행 벡터 변환 ===')
"""
reshape를 사용한 벡터 형태 변환:
- 행 벡터: (1, n)
- 열 벡터: (n, 1)
"""
arr = np.array([1, 2, 3, 4, 5])
print('원본 배열:', arr, '| shape:', arr.shape)

# 행 벡터 (1행 n열)
row_vector = arr.reshape(1, -1)
print('\n행 벡터:\n', row_vector, '| shape:', row_vector.shape)

# 열 벡터 (n행 1열)
col_vector = arr.reshape(-1, 1)
print('\n열 벡터:\n', col_vector, '| shape:', col_vector.shape)
print()

print('=== 7. reshape 오류 예시 ===')
"""
요소 개수가 맞지 않으면 오류 발생
"""
arr = np.arange(12)  # 12개 요소
print('배열 크기:', arr.size)

try:
    wrong_reshape = arr.reshape(3, 5)  # 3 * 5 = 15 (불가능)
except ValueError as e:
    print('오류 발생:', e)
print()

print('=== 8. 실전 예제: 이미지 데이터 변환 ===')
"""
이미지 처리에서 reshape는 필수:
- (높이, 너비, 채널) ↔ (배치, 높이, 너비, 채널)
- 2D ↔ 1D (머신러닝 입력)
"""
# 가상의 RGB 이미지 데이터 (28x28x3)
image = np.random.randint(0, 256, size=(28, 28, 3))
print('원본 이미지 shape:', image.shape)  # (28, 28, 3)

# 1D 벡터로 펼치기 (머신러닝 입력용)
image_flat = image.reshape(-1)
print('펼친 이미지 shape:', image_flat.shape)  # (2352,)

# 다시 원래 형태로 복원
image_restored = image_flat.reshape(28, 28, 3)
print('복원된 이미지 shape:', image_restored.shape)  # (28, 28, 3)
print('복원 성공?', np.array_equal(image, image_restored))  # True
print()

print('=== 9. 배치 처리를 위한 reshape ===')
"""
딥러닝에서 자주 사용하는 패턴
"""
# 100개의 28x28 흑백 이미지
images = np.random.rand(100, 28, 28)
print('이미지 데이터 shape:', images.shape)

# 각 이미지를 1D로 펼치기 (100, 784)
images_flat = images.reshape(100, -1)
print('펼친 데이터 shape:', images_flat.shape)

# 다시 원래 형태로
images_restored = images_flat.reshape(100, 28, 28)
print('복원된 데이터 shape:', images_restored.shape)
print()

print('=== 10. newaxis를 사용한 차원 추가 ===')
"""
reshape의 대안: np.newaxis
- 새로운 차원을 추가할 때 더 직관적
- None과 동일
"""
arr = np.array([1, 2, 3, 4, 5])
print('원본:', arr.shape)

# 행 벡터 (1, 5)
row = arr[np.newaxis, :]
print('행 벡터:', row.shape)

# 열 벡터 (5, 1)
col = arr[:, np.newaxis]
print('열 벡터:', col.shape)
print()


# ============================================================================
# 핵심 정리
# ============================================================================
"""
np.random.normal() 핵심:
1. 정규 분포(가우시안 분포) 난수 생성
2. loc(평균), scale(표준편차), size(배열 크기) 지정
3. 실제 데이터 시뮬레이션에 유용
4. randn()보다 유연하지만 조금 느림

reshape() 핵심:
1. 배열의 형태를 변경 (전체 요소 개수는 동일)
2. 원본은 변경하지 않음 (새 view 반환)
3. -1 사용으로 자동 크기 계산 가능
4. 이미지/텐서 데이터 변환에 필수
5. flatten(), ravel()로 1D 변환 가능

주의사항:
- reshape는 요소 개수가 맞아야 함
- normal()은 충분히 큰 샘플에서 평균/표준편차가 정확함
"""

print('=' * 70)
print('normal()과 reshape() 학습 완료!')
print('=' * 70)

=== 1. 기본 사용법 ===
랜덤 숫자 10개: [ 0.27904129  1.01051528 -0.58087813 -0.52516981 -0.57138017 -0.92408284
 -2.61254901  0.95036968  0.81644508 -1.523876  ]

=== 2. 평균 지정하기 ===
시험 점수 10개: [ 93.57930904  88.86389744  89.44984297  67.90569016  90.55787559
 108.965807   138.39232047 105.91349533 101.83328748  92.26846507]
평균: 97.8

=== 3. 2차원 배열로 만들기 ===
3x4 랜덤 배열:
 [[43.9974615  59.47439821 52.91034001 43.6444026 ]
 [39.78447805 48.38244614 44.66351196 49.94472138]
 [47.70549546 53.89348913 37.34880886 60.91992264]]

=== 4. 실전 예제: 키 데이터 만들기 ===
키 10명: [189.4, 178.4, 171.5, 176.2, 162.9, 158.9, 175.4, 166.2, 160.6, 163.8]
평균 키: 170.3 cm
가장 큰 키: 193.6 cm
가장 작은 키: 151.4 cm

=== 1. 기본 reshape ===
원본 배열: [ 0  1  2  3  4  5  6  7  8  9 10 11]
원본 shape: (12,)

3x4로 변환:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
변환 후 shape: (3, 4)

=== 2. 다양한 형태로 변환 ===
2x12 행렬:
 [[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]

4x6 행렬:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12