# 인덱싱 슬라이싱 


# 뷰 

In [47]:
import numpy as np
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr[0, 0])
print(arr[2, 1])

matrix = [[1, 2, 3], [4, 5, 6]]
print(matrix[1][2])    

arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr[1, 2])

arr = np.arange(24).reshape(2, 3, 4)
print(arr[0, 1, 2])

arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])
print(arr[:3])
print(arr[2:])
print(arr[::2])

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr[:2, 1:])

arr = np.array([10, 20, 30, 40, 50])
sub_arr = arr[1:3]
sub_arr[0] = 99
print(arr)

arr = np.array([1, 2, 3])
view_arr = arr.view()
view_arr[0] = 99
print(view_arr)

copy_arr = arr.copy()
copy_arr[1] = 100
print(arr)
print(copy_arr)

arr = np.array([10, 20, 30, 40, 50])
print(arr[[0, 2, 4]])

arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 30])

1
8
6
6
6
[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]
[[2 3]
 [5 6]]
[10 99 30 40 50]
[99  2  3]
[99  2  3]
[ 99 100   3]
[10 30 50]
[40 50]


In [58]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("=== 1차원 배열===")
print("shape: ", arr_1d.shape)
print("ndim", arr_1d.ndim)
print(arr_1d.reshape(4, -1))
print("size", arr_1d.size)
print()
print("=== 2차원 배열===")
print("shape: ", arr_2d.shape)
print("ndim", arr_2d.ndim)
print("size", arr_2d.size)

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])


print("배열 a:", a)
print("배열 b:", b)


print("덧셈 (a + b): ", a + b)
print("뺼셈 (a - b): ", a - b)
print("곱셈 (a * b): ", a * b)
print("거듭제곱 (a ** b):", a**b)
print("나눗셈 (a / b): ", a / b)
print("몫 (a // b): ", a // b)
print("나머지 (a % b): ", a % b)

a = np.array([1, 2, 3, 4, 5])

print("스칼라", )
print("스칼라", )
print("스칼라", )
print("스칼라", )
print("스칼라", )



=== 1차원 배열===
shape:  (12,)
ndim 1
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
size 12

=== 2차원 배열===
shape:  (2, 3)
ndim 2
size 6
배열 a: [1 2 3 4 5]
배열 b: [10 20 30 40 50]
덧셈 (a + b):  [11 22 33 44 55]
뺼셈 (a - b):  [ -9 -18 -27 -36 -45]
곱셈 (a * b):  [ 10  40  90 160 250]
거듭제곱 (a ** b): [          1     1048576 -1010140999           0  1296002393]
나눗셈 (a / b):  [0.1 0.1 0.1 0.1 0.1]
몫 (a // b):  [0 0 0 0 0]
나머지 (a % b):  [1 2 3 4 5]
스칼라
스칼라
스칼라
스칼라
스칼라


In [ ]:
# 배열 연산(1)
# 문제 1
arr = np.array([1, 2, 3, 4])
print(arr + 3)
print()

# 문제 2
arr = np.array([[5, 10],
                [15, 20]])
print(arr * -1)


# 문제 3
arr1 = np.array([2, 4, 6])
arr2 = np.array([1, 2, 3])
print("곱셈: ", arr1 * arr2)
print("나눗셈: ", arr1 // arr2)

# 문제 4
arr = np.array([[95, 97],
                [80, 85]])

target = 100

d = target - arr

result = arr + d
print("최대값 100으로 만들기 위해 필요한 값을 더한 결과: ", result)


# 문제 5
arr = np.array([[1, 2, 3], [4, 5, 6]]) 

n1 = 10
n2 = 100

result1 = arr[0] * n1
print(result1)
result2 = arr[1] * n2
print(result2)

# 문제 6
arr = np.array([[10, 20], 
                [30, 40],
                [50, 60]])

arr_1 = np.array([[100],
                 [200],
                 [300]])

print((arr + arr_1))





[4 5 6 7]

[[ -5 -10]
 [-15 -20]]
곱셈:  [ 2  8 18]
나눗셈:  [2 2 2]

[[ 2  8 18]
 [ 8 20 36]]

[[110 120]
 [230 240]
 [350 360]]


In [83]:
from numpy.random import default_rng
import numpy as np

# 문제 4
rng = default_rng(seed=42)

arr = rng.integers(0, 10, size=(4, 4), dtype=np.int32)

main_diag = []
for i in range(arr.shape[0]):
    main_diag.append(arr[i, i])

anti_diag = []
n = arr.shape[0]
for i in range(n):
    anti_diag.append(arr[i, n - i - 1])

print("문제 4.")
print("주대각선:", repr(main_diag))
print("부대각선:", repr(anti_diag))
print()

# 문제 5
arr = np.random.randint(0, 9, (3, 4, 5))
print("문제 5.")
print("두 번째 층의 첫 행 마지막 열 값: ", arr[1, 0, -1])

문제 4.
주대각선: [0, 8, 5, 7]
부대각선: [4, 0, 0, 7]

문제 5.
두 번째 층의 첫 행 마지막 열 값:  0
