In [1]:
import numpy as np

number = np.random.normal(100, 20, size = 6)
print(number)

[151.28688142 109.46868036  98.02659741 100.21773102  82.32701147
  79.43794503]


In [2]:
import numpy as np
print(np.random.randn(2, 3))

[[-0.7131388   0.05965794  0.54512202]
 [-2.2330471  -1.11597747  0.9520469 ]]


In [3]:

print(np.arange(0, 22, 2))

[ 0  2  4  6  8 10 12 14 16 18 20]


In [4]:
import numpy as np
print(np.full((3, 4), 5))

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [5]:
import numpy as np

number = np.resize(np.arange(1, 21), (4, 5))
print(number)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [6]:
import numpy as np

number = np.random.uniform(0, 1, size=(3, 4))
print(number)

[[0.98131682 0.49328831 0.85261272 0.89036705]
 [0.47670731 0.04167962 0.78137676 0.56423595]
 [0.27950535 0.01196782 0.79003824 0.05107639]]


In [7]:
import numpy as np

number = np.random.randint(0, 100, (10, 10))
a = np.eye(10)
result = number + a
print(result)

[[57. 32. 89. 15. 54. 83. 67. 47. 76. 56.]
 [89. 57. 10.  5. 85. 79. 30. 22. 99. 70.]
 [38. 69. 22. 94. 44. 56.  1. 37. 44. 92.]
 [58. 73.  4. 34. 61. 56. 32.  5. 41. 43.]
 [66. 90. 34. 25. 56. 78.  5. 33. 21. 65.]
 [35. 17. 38. 95. 55. 41. 54. 72. 47. 31.]
 [ 6.  6. 90. 38. 16. 90. 15. 13. 65. 64.]
 [24. 93. 85. 30. 30. 15. 51. 87.  9. 54.]
 [93. 78. 60. 20. 41. 67. 27. 48. 86. 38.]
 [70. 74. 32. 45. 24. 89. 80.  6. 31. 31.]]


In [8]:
import numpy as np

number = np.random.randint(0, 10, (2, 3, 4))
print(number)

[[[6 7 3 7]
  [8 1 6 5]
  [3 6 2 8]]

 [[2 7 2 7]
  [9 8 5 6]
  [1 4 8 0]]]


In [9]:
import numpy as np

arr = np.arange(10, 30, 2) 
print(arr[[1, 3, 5]])

[12 16 20]


In [10]:
import numpy as np
arr = np.arange(1, 10).reshape(3, 3)
arr2 = np.array(arr)
arr3 = [arr2[0, 0], arr2[1, 1], arr2[2, 2]]
print(f"[{' '.join(map(str, arr3))}]")

[1 5 9]


In [11]:
import numpy as np
arr = np.arange(1, 13).reshape(3, 4)
arr2 = np.array(arr)
sub_arr = arr2[:2:, 1:]
sub_arr[2] = "-1"
print(arr2)

IndexError: index 2 is out of bounds for axis 0 with size 2